version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app/sampleApp
    working_dir: /app/sampleApp
    container_name: sampleApp
    command: sh -c "cd react-sample && yarn start"
    tty: true
